global using AutoMapper;
global using FluentValidation;
global using MAILSYSTEM.APPLICATION.Abstractions.Messaging;
global using MAILSYSTEM.APPLICATION.Contracts;
global using MAILSYSTEM.DOMAIN.Entities;
global using MAILSYSTEM.DOMAIN.Repositories;
global using MAILSYSTEM.DOMAIN.Responses.Companies;
global using MAILSYSTEM.DOMAIN.Shared;
global using MediatR;
